name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.0

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run EUnit tests
      run: rebar3 as test eunit
    - name: Run CT tests
      run: rebar3 as test ct --sys_config ./config/test.config --spec ./test/specs/all.spec --sname tests --readable true --basic_html false
